version: "3.8"
services:
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    container_name: kafka
    hostname: ${HOSTNAME}
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=hbase:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - hbase

  hbase:
    build: 
      context: ./hbase
      network: host
    container_name: hbase
    hostname: ${HOSTNAME}
    ports:
      - 60000:60000 # master
      - 60010:60010 # master-ui
      - 60020:60020 # rs
      - 60030:60030 # rs-ui
      - 2181:2181   # zookeeper

volumes:
  kafka_data:
