version: "3.8"
services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: ${KAFKA_ADVERTISED_HOST}
    ports:
      - 9092:9092
    depends_on:
      - hbase
    environment:
      KAFKA_CREATE_TOPICS: ${KAFKA_TOPICS}
      KAFKA_ZOOKEEPER_CONNECT: hbase:2181
    links:
      - hbase

  hbase:
    build: 
      context: ./hbase
      network: host
    container_name: hbase
    hostname: ${HOSTNAME}
    ports:
      - 60000:60000 # master
      - 60010:60010 # master-ui
      - 60020:60020 # rs
      - 60030:60030 # rs-ui
      - 2181:2181   # zookeeper
